# Generated by Django 4.2.5 on 2023-10-03 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadrinho', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('DC', 'DC'), ('MARVEL', 'Marvel'), ('IMAGE COMICS', 'Image Comics'), ('CGC', 'CGC')], default='', max_length=100)),
                ('categoria_favoritos', models.CharField(choices=[('BATMAN', 'Batman'), ('SUPERMAN', 'Superman'), ('HOMEM ARANHA', 'Homem aranha'), ('VINGADORES', 'Vingadores'), ('LIGA DA JUSTIÇA', 'Liga da Justiça')], default='', max_length=100)),
                ('roterista', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('arte_capa', models.CharField(max_length=100)),
                ('prevenda', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('disponivel', models.TextField(default=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('foto', models.ImageField(blank=True, upload_to='Fotos/%Y/%m/%d/')),
                ('preco', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
