# Generated by Django 4.2.5 on 2023-10-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_loja_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='categoria',
            field=models.CharField(choices=[('DC', 'DC'), ('MARVEL', 'Marvel'), ('IMAGE COMICS', 'Image Comics'), ('CGC', 'CGC')], default=None, max_length=100),
        ),
    ]
