# Generated by Django 4.2.5 on 2023-10-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_loja_categoria_alter_loja_categoria_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='categoria_favoritos',
            field=models.CharField(choices=[('', ''), ('BATMAN', 'Batman'), ('SUPERMAN', 'Superman'), ('HOMEM ARANHA', 'Homem aranha'), ('VINGADORES', 'Vingadores'), ('LIGA DA JUSTIÇA', 'Liga da Justiça')], default='', max_length=100),
        ),
    ]
