# Generated by Django 4.2.5 on 2023-10-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_loja_categoria_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='categoria',
            field=models.CharField(choices=[('DC', 'DC'), ('MARVEL', 'Marvel'), ('IMAGE COMICS', 'Image Comics'), ('CGC', 'CGC')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='loja',
            name='categoria_favoritos',
            field=models.CharField(choices=[('a', 'a'), ('BATMAN', 'Batman'), ('SUPERMAN', 'Superman'), ('HOMEM ARANHA', 'Homem aranha'), ('VINGADORES', 'Vingadores'), ('LIGA DA JUSTIÇA', 'Liga da Justiça')], default='', max_length=100),
        ),
    ]
