# Generated by Django 4.2.5 on 2023-12-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_loja_categoria_alter_loja_categoria_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='categoria_favoritos',
            field=models.CharField(choices=[('a', 'a'), ('BATMAN', 'Batman'), ('SUPERMAN', 'Superman'), ('HOMEM ARANHA', 'Homem aranha'), ('FLASH', 'Flash'), ('MULHER MARAVILHA', 'Mulher Maravilha'), ('HOMEM DE FERRO', 'Homem de Ferro'), ('HULK', 'Hulk')], default='a', max_length=100),
        ),
    ]
